CC = gcc
FLAG = -std=c11 -Wno-switch
FILES = ./util/error.c ./env/enviroment.c ./lexer/lexer.c ./parser/parser.c ./interpreter/interpreter.c opp.c
EXE = o++

all:
	$(CC) $(FLAG) $(FILES) -o o++

clean:
	rm o++
